name:                 worms
version:              0.0.0.0
visibility:           public
id:                   worms-0.0.0.0-inplace
key:                  worms-0.0.0.0-inplace
author:
    João Maria Oliveira Pontes <a111657@alunos.uminho.pt>
    João Paulo Pires Cascais <a110393@alunos.uminho.pt>

category:             Game
abi:                  inplace
exposed:              True
exposed-modules:
    Labs2025 Tarefa0_2025 Tarefa0_geral Tarefa1 Tarefa2 Tarefa3

import-dirs:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/build

library-dirs:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/build

library-dirs-static:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/build

dynamic-library-dirs:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/build

data-dir:             /Users/joaomariapontes/2025l1g090/2025l1g090/.
hs-libraries:         HSworms-0.0.0.0-inplace
depends:              base-4.17.2.1
haddock-interfaces:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/doc/html/worms/worms.haddock

haddock-html:
    /Users/joaomariapontes/2025l1g090/2025l1g090/dist-newstyle/build/aarch64-osx/ghc-9.4.8/worms-0.0.0.0/doc/html/worms
